apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookwatch-back
spec:
  serviceName: "back"
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: ghcr.io/aitorru/bookwatch-back-2def1062e25d2892a74855d35756f2ef15b6cb20:trunk
        ports:
        - containerPort: 3001
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: DB_HOST
          value: "mongodb"