apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookwatch-front
spec:
  serviceName: "front"
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: ghcr.io/aitorru/bookwatch-front-2def1062e25d2892a74855d35756f2ef15b6cb20:trunk
        ports:
        - containerPort: 3000
        env:
          - name: BACK_HOST
            value: back
