name: GitHub Actions - Back Image Build
run-name: Back docker image building
on: [push]
jobs:
  Build-DockerImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd back && docker build -t back .