name: GitHub Actions - Front Image Build
run-name: Front docker image building
on: [push]
jobs:
  Build-DockerImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd front && docker build -t front .